# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gaurav256/helloworld
  pullPolicy: IfNotPresent
  tag: 1.0.0

container:
  name: helloworld
  port: 8080


securityContext: 
   allowPrivilegeEscalation: true
   runAsNonRoot: false

service:
  name: helloworld-service
  type: NodePort
  port: 8080


resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  name: helloworld-hpa
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  

database:
  username : "user123"
  password : "testuser"

