apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      {{- include "demo.matchlabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}  
  template:
    metadata:
      {{- include "demo.labels" . | nindent 6 }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}